config/routes.rb
Rails.application.routes.draw do

  resources :measure_periods
  devise_for :users

  resources :measures, except: [:show, :update, :edit]

  authenticated :user do
    root to: 'measures#index', as: :auth_root
  end

  unauthenticated do
    root to: 'pages#show', id: 'home', as: :unauth_root
  end

end

app/models/measure.rb
class Measure < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :systolic, :diastolic, presence: true
end

app/models/measure_period.rb
class MeasurePeriod < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :starting_day, :number_of_days, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :measure_periods, dependent: :destroy
  has_many :measures, dependent: :destroy

  MEASURE_SUBNISSIONS_NEEDED = 3

  def average_available?
    return measures.count >= MEASURE_SUBNISSIONS_NEEDED
  end

  def average_systolic
    if average_available?
      measures.average(:systolic).round(2)
    else
      nil
    end
  end

  def average_diastolic
    if average_available?
      measures.average(:diastolic).round(2)
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/measure_periods_controller.rb
class MeasurePeriodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_measure_period, only: [:show, :edit, :update, :destroy]

  # GET /measure_periods
  # GET /measure_periods.json
  def index
    @measure_periods = MeasurePeriod.all
  end

  # GET /measure_periods/1
  # GET /measure_periods/1.json
  def show
  end

  # GET /measure_periods/new
  def new
    @measure_period = MeasurePeriod.new
  end

  # GET /measure_periods/1/edit
  def edit
  end

  # POST /measure_periods
  # POST /measure_periods.json
  def create
    @measure_period = current_user.measure_periods.build(measure_period_params)

    respond_to do |format|
      if @measure_period.save
        format.html { redirect_to action: :index, notice: 'Measure period was successfully created.' }
        format.json { render :show, status: :created, location: @measure_period }
      else
        format.html { render :new }
        format.json { render json: @measure_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measure_periods/1
  # PATCH/PUT /measure_periods/1.json
  def update
    respond_to do |format|
      if @measure_period.update(measure_period_params)
        format.html { redirect_to @measure_period, notice: 'Measure period was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure_period }
      else
        format.html { render :edit }
        format.json { render json: @measure_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measure_periods/1
  # DELETE /measure_periods/1.json
  def destroy
    @measure_period.destroy
    respond_to do |format|
      format.html { redirect_to measure_periods_url, notice: 'Measure period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure_period
      @measure_period = MeasurePeriod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_period_params
      params.require(:measure_period).permit(:starting_day, :number_of_days)
    end
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_measure, only: [:destroy]

  # GET /measures
  # GET /measures.json
  def index
    @measures = current_user.measures
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # POST /measures
  # POST /measures.json
  def create
    @measure = current_user.measures.build(measure_params)

    respond_to do |format|
      if @measure.save
        format.html { redirect_to action: :index, notice: 'Measure was successfully created.' }
        format.json { render :show, status: :created, location: @measure }
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to measures_url, notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:systolic, :diastolic, :pulse)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage

  # before_filter :authenticate
  # layout :layout_for_page

  private

  def layout_for_page
    case params[:id]
    when 'home'
      'home'
    else
      'application'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/measure_periods_helper.rb
module MeasurePeriodsHelper
end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<div class="nav-head clearfix">
  <div class="inner">
    <h3 class="nav-brand">
      <%= image_tag 'logo.png', :class => "logo"%>
      TrackTension
    </h3>
    <nav>
      <ul class="nav">
        <% if user_signed_in? %>
          <%= active_link_to t('nav.measure_periods'), measure_periods_path, :wrap_tag => :li %>
          <%= active_link_to t('nav.measures'), measures_path, :wrap_tag => :li %>
          <%= active_link_to t('nav.edit_account'), edit_user_registration_path, :wrap_tag => :li %>
          <li><%= link_to t('homeNav.logout'), destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <%= active_link_to t('nav.home'), unauth_root_path, active: :exclusive, :wrap_tag => :li %>
          <%= active_link_to t('nav.signin'), new_user_session_path, :wrap_tag => :li %>
          <%= active_link_to t('nav.signup'), new_user_registration_path, :wrap_tag => :li %>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackTension | <%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash_messages %>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <%= render 'layouts/navigation' %>
        <div class="inner cover">
          <%= yield %>
        </div>
        <footer>
          <div class="inner">
            <p>Find source code <a href="https://github.com/ThibaudD">here</a>, by <a href="https://github.com/ThibaudD">Thib</a>.</p>
          </div>
        </footer>
      </div>
    </div>
  </div>
</body>
</html>

app/views/measure_periods/_form.html.erb
<%= form_for(@measure_period, html: { class: 'form-horizontal' }) do |f| %>
  <% if @measure_period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measure_period.errors.count, "error") %> prohibited this measure_period from being saved:</h2>

      <ul>
      <% @measure_period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :starting_day %><br>
    <%= f.date_select :starting_day %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :number_of_days %>
    <% days_array = (3..7).to_a.map { |day| ["#{day} days", day] } %>
    <%= f.select :number_of_days, options_for_select(days_array) %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/measure_periods/edit.html.erb
<h1>Editing Measure Period</h1>

<%= render 'form' %>

<%= link_to 'Show', @measure_period %> |
<%= link_to 'Back', measure_periods_path %>

app/views/measure_periods/index.html.erb
<% provide(:title, "Measure periods") %>

<h1>Listing Measure Periods</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Starting day</th>
      <th>Number of days</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @measure_periods.each do |measure_period| %>
      <tr>
        <td><%= I18n.localize measure_period.starting_day, format: :long %></td>
        <td><%= measure_period.number_of_days %></td>
        <td>
          <%= link_to measure_period, method: :get do %>
            Show <i class="glyphicon glyphicon-menu-right"></i>
          <% end %>
        </td>
        <td>
          <%= link_to measure_period, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-link" do %>
            <i class="glyphicon glyphicon-remove-circle"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measure period', new_measure_period_path, class: "btn btn-default" %>

app/views/measure_periods/new.html.erb
<h1>New Measure Period</h1>

<%= render 'form' %>

<%= link_to measure_periods_path, class: "btn btn-default" do %>
  <i class="glyphicon glyphicon-menu-left"></i> Back
<% end %>

app/views/measure_periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starting day:</strong>
  <%= @measure_period.starting_day %>
</p>

<p>
  <strong>Number of days:</strong>
  <%= @measure_period.number_of_days %>
</p>

<%= link_to 'Edit', edit_measure_period_path(@measure_period) %> |
<%= link_to 'Back', measure_periods_path %>

app/views/measures/_form.html.erb
<%= form_for(@measure, html: { class: 'form-inline' }) do |f| %>
  <% if @measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% @measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :systolic, class: "sr-only" %>
    <%= f.text_field :systolic, class: "form-control", placeholder: :systolic %>
  </div>
  <div class="form-group">
    <%= f.label :diastolic, class: "sr-only" %>
    <%= f.text_field :diastolic, class: "form-control", placeholder: :diastolic %>
  </div>
  <div class="form-group">
    <%= f.label :pulse, class: "sr-only" %>
    <%= f.text_field :pulse, class: "form-control", placeholder: :pulse %>
  </div>
  <div class="form-group">
    <div class="">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/measures/edit.html.erb
<h1>Editing Measure</h1>

<%= render 'form' %>

<%= link_to 'Show', @measure %> |
<%= link_to 'Back', measures_path %>

app/views/measures/index.html.erb
<% provide(:title, "Measures") %>

<h1>Listing Measures</h1>

<% if current_user.average_available? %>
<div class="average">
  <h4>Average</h4>
  Systolic: <%= current_user.average_systolic %> mm Hg
  Diastolic: <%= current_user.average_diastolic %> mm Hg
</div>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>
        Date
      </th>
      <th>Systolic (mm Hg)</th>
      <th>Diastolic (mm Hg)</th>
      <th>Pulse (BPMs)</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @measures.each do |measure| %>
      <tr>
        <td><%= I18n.localize measure.created_at, format: :long %></td>
        <td><%= measure.systolic %></td>
        <td><%= measure.diastolic %></td>
        <td><%= measure.pulse %></td>
        <td>
          <%= link_to measure, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="glyphicon glyphicon-remove-circle"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measure', new_measure_path, class: "btn btn-default" %>

app/views/measures/new.html.erb
<% provide(:title, "New Measure") %>
<h1>New Measure</h1>

<%= render 'form' %>
<br>
<%= link_to measures_path, class: "btn btn-default" do %>
  <i class="glyphicon glyphicon-menu-left"></i> Back
<% end %>

app/views/measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Systolic:</strong>
  <%= @measure.systolic %>
</p>

<p>
  <strong>Diastolic:</strong>
  <%= @measure.diastolic %>
</p>

<p>
  <strong>Pulse:</strong>
  <%= @measure.pulse %>
</p>

<p>
  <strong>User:</strong>
  <%= @measure.user %>
</p>

<%= link_to 'Edit', edit_measure_path(@measure) %> |
<%= link_to 'Back', measures_path %>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<section class="landing">

</section>


<h1 class="cover-heading">Track your blood pressure</h1>
<p class="lead">Save and visualize the evolution of your blood pressure</p>
<p class="lead">
  <%= link_to t('homeNav.signup'), new_user_registration_path, class: "btn btn-lg btn-default" %>
</p>